import Navbar from "@/component/navbar";
import { Inter } from "next/font/google";
import "./globals.css";
import "./../../node_modules/bootstrap/dist/css/bootstrap.min.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "triColab Technology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="main">
          {children}

        </main>
      </body>
    </html>
  );
}
